### ISSUE TITLE
where is files directory?

### ISSUE THREAD

**Issue by sinath72** [TechShreyash/TG-Direct-Link-Generator#3]
hello
i send files on telegram bot 
i want to know where is my files directory to access that on server

**Comment by TechShreyash** [comment]
@sinath72 The files are just actually stored on telegram server

**Comment by sinath72** [comment]
ok thanks 
what can i do run in background bot and doing another command in one season ssh terminal

**Comment by TechShreyash** [comment]
@sinath72 Use tmux or screen

**Comment by ghost** [comment]
@sinath72 You can use tmux or screen for that
